#!/usr/bin/env ruby

load 'acv_exporter.rb'

file_path           = ARGV[0]
image_path          = ARGV[1]
output_image_path   = ARGV[2]

raise "You have to specify a valid input image path and output path" unless image_path && File.exist?(image_path) && output_image_path

acv = ACVExporter.new(file_path)

acv.export_image(image_path, output_image_path)